### ISSUE TITLE
 Blockrange ??? not ready yet

### ISSUE THREAD

**Issue by canteboi** [chainpoint/chainpoint-node#50] opened 2017-09-21 13:11 UTC
hello, any advise why am I getting this?

![image](https://user-images.githubusercontent.com/6516873/30697376-627471c8-9f11-11e7-9dd1-ed74465abca7.png)

**Comment by grempe** [comment] 2017-09-21 20:32
Closing as duplicate of #40 

Not an error, and this log message will be removed in the next release.

https://github.com/chainpoint/chainpoint-node/issues/40#issuecomment-330877092

**Closed by grempe** 2017-09-21 20:32 UTC
