### ISSUE TITLE
I delete .data file and the node can not start

### ISSUE THREAD

**Issue by aona11** [chainpoint/chainpoint-node#9] opened 2017-09-17 16:13 UTC
Hi, dev 

For the node stop at 15235 . I want reinstall my node .so I  install and delete .data file 
But the log belows 

`chainpoint-node_1  | 2017-09-17T15:58:36.363209986Z A NodeHMAC does not exist locally for TNT address 0x78a040e50c6f059ad6bd35686b9b1fc1ba2ddaad
chainpoint-node_1  | 2017-09-17T15:58:36.620890424Z TNT address 0x78a040e50c6f059ad6bd35686b9b1fc1ba2ddaad cannot be registered, it is already registered and in use with an existing HMAC key
chainpoint-node_1  | 2017-09-17T15:58:36.627518852Z error Command failed with exit code 1.`

I have backup my private auth key . How can I make the program work well ?

**Comment by accrubit** [comment] 2017-09-17 19:57
I have the same issue on one of my nodes and need to know how to reestablish my key with my node

**Comment by grempe** [comment] 2017-09-20 15:35
Closing as duplicate of #12

**Closed by grempe** 2017-09-20 15:35 UTC
