### ISSUE TITLE
No local Node authentication key for TNT

### ISSUE THREAD

**Issue by longnh88888** [chainpoint/chainpoint-node#56] opened 2017-09-23 04:12 UTC
Hello !
My host had accidently down, and I have just reinstalled the Node on another host, then the Node does not run with this message:

No local Node authentication key for TNT address    xxxx    Registering.
TNT address    xxxxx    is already in use and cannot be registered
![screenshot_7](https://user-images.githubusercontent.com/32213407/30770046-d0eacfd6-a050-11e7-8fa4-33e1bc1e21a1.jpg)

May be it tried to register new Node
Please help how to import my private key into host to continue running the Node with my registered ETH address before on Core

Thank you !

**Comment by longnh88888** [comment] 2017-09-23 06:02
Unfortunately, I have just read this: 

![screenshot_1](https://user-images.githubusercontent.com/32213407/30770611-4b9afaa4-a05f-11e7-8cc7-6fcc422f374f.jpg)

**Comment by grempe** [comment] 2017-09-23 19:22
Closing. Duplicate of #12

**Closed by grempe** 2017-09-23 19:22 UTC
