### ISSUE TITLE
Error performing Calendar update

### ISSUE THREAD

**Issue by bokiim** [chainpoint/chainpoint-node#60] opened 2017-09-24 08:52 UTC
I have this line in my logs, is it ok ? 
Error performing Calendar update

and when I check on a.chaipoint.org, the last time is today at 6:15, so 3 hours behind...

The rest looks ok, it's even submitting hashes etc.

**Comment by grempe** [comment] 2017-09-26 17:24
Closing as duplicate of issue #69

**Closed by grempe** 2017-09-26 17:24 UTC
