### ISSUE TITLE
Error Code 137 (Unofficial Solution Enclosed)

### ISSUE THREAD

**Issue by accrubit** [chainpoint/chainpoint-node#53] opened 2017-09-22 21:16 UTC

**Comment by jupiter126** [comment] 2017-09-22 21:18
One liner error 137 solution:
sudo bash -c 'fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' » /etc/fstab'

**Comment by jupiter126** [comment] 2017-09-22 23:07
same, but takes space left and username in consideration:
frspace=$(df | grep "/$"| awk '{ print $4 }'|tr -d ' ')&&if [[ "$frspace" -gt "1600000" ]]; then if [[ "$(whoami)" = "root" ]]; then fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' » /etc/fstab;else sudo bash -c 'fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' » /etc/fstab';fi;else echo "Disk space on / too low to create swap partition"; fi

**Comment by jupiter126** [comment] 2017-09-22 23:12
now checks if file doesn't exist, if there's enough space, and which user is running the command:

if [[ ! -f /swapfile ]]; then frspace=$(df | grep "/$"| awk '{ print $4 }'|tr -d ' ')&&if [[ "$frspace" -gt "1600000" ]]; then if [[ "$(whoami)" = "root" ]]; then fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' » /etc/fstab;else sudo bash -c 'fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' » /etc/fstab';fi;else echo "Disk space on / too low to create swap partition"; fi; else echo "swapfile already exists";fi

**Comment by jupiter126** [comment] 2017-09-22 23:21
if [[ ! -f /swapfile ]]; then frspace=$(df | grep "/$"| awk '{ print $4 }'|tr -d ' ')&&if [[ "$frspace" -gt "6000000" ]]; then if [[ "$(whoami)" = "root" ]]; then fallocate -l 4G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' » /etc/fstab;else sudo bash -c 'fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' » /etc/fstab';fi;else echo "Disk space on / too low to create swap partition"; fi; else echo "swapfile already exists";fi

**Comment by memopo** [comment] 2017-09-23 09:06
is it related to : 
cannot get node config for http://x.x.x.x: Error: ESOCKETTIMEDOUT
when send hash with chp to x.x.x.x ?

**Comment by jupiter126** [comment] 2017-09-23 17:10
Maybe cleaner:

cd chainpoint-node
if [[ "$(ls -lh /swapfile |cut -f5 -d" ")" != "2.0G" ]]; then
	make down && swapoff /swapfile && rm /swapfile
fi
if [[ ! -f /swapfile ]]; then
	frspace=$(df | grep "/$"| awk '{ print $4 }'|tr -d ' ')
	if [[ "$frspace" -gt "3000000" ]]; then
		make down && sleep 3
		fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
	else
		echo "Disk space on / too low to create swap partition"
	fi
fi
sudo -u $user make up
if [[ "$(cat /etc/fstab|grep '/swapfile none swap sw 0 0')" = "" ]]; then
	echo '/swapfile none swap sw 0 0' » /etc/fstab
fi
sed -i '/\/swapfile none swap sw 0 0/{1!d}' /etc/fstab

**Comment by adamluc** [comment] 2017-09-23 17:55
+1

**Comment by grempe** [comment] 2017-09-23 19:28
Can you at least properly markdown fence the code samples above so people can view them properly?

**Comment by jupiter126** [comment] 2017-09-23 19:40
I'm out, posted solution in a hurry to help before i left... somehow
comment section eats ident... will correct later
If you're in a hurry, theres an indented copy in my updaetierion_2.sh alpha
script, cfr my github shared many times

**Comment by grempe** [comment] 2017-09-23 19:42
I added markdown fencing to @jupiter126 comments for readability.

**Comment by grempe** [comment] 2017-09-23 19:43
Please keep in mind. This is a workaround, and does not resolve the root cause of the issue, which is likely insufficient RAM on the host server.

**Comment by jupiter126** [comment] 2017-09-23 19:44
Absolutely, i don't use it myself.

**Comment by Chikashi-Kato** [comment] 2017-09-24 08:00
If you cannot fix the code 137 error with the workaround, try my solution posted in #46

**Comment by n0bility6** [comment] 2017-09-24 14:55
Hi Guyz,

Create Swap File

#dd if=/dev/zero of=/mnt/myswap.swap bs=512K count=2000    //1GB Swap
#mkswap /mnt/myswap.swap
#swapon /mnt/myswap.swap

#nano /etc/fstab
#/mnt/myswap.swap none swap sw 0 0

**Comment by jupiter126** [comment] 2017-09-24 19:02
updated previous answer, code identing correct now

**Comment by sgarciafer** [comment] 2017-10-01 19:33
I get that same error, but I doubt is a memory issue, as my "top" command show I have less than 1% of the CPU in use. Also, enabling the swap partitions doesn't seem to solve the problem.

**Comment by sgarciafer** [comment] 2017-10-02 03:21
Solution from @jupiter126 worked on many cases. On others doesn't.
One of the nodes using a DigitalOcean dropplet with Ubuntu 16.04 get stuck with the error code 137 even by rising the swap file to 4Gb. Made down then up doesn't solved the issue neither.

**Comment by grempe** [comment] 2017-10-02 14:38
While we appreciate the guidance from people on this thread, this error is the result of operating a Node on a server that just doesn't have enough RAM. We now officially recommend a minimum of 1GB of RAM. We cannot provide general guidance on the mechanism for adding a swapfile (which is really just a bandaid on the lack of RAM) because this may vary from OS to OS. If there is sufficient interest in supporting the addition of a swap file we would accept a pull request (that targets Ubuntu 16.04 only) to the Makefile to add a task to simplify creation of a swapfile on that OS. Pending that, and since this is not a 'bug' that we can 'fix' I am closing this issue. Thx

**Closed by grempe** 2017-10-02 14:38 UTC
