### ISSUE TITLE
Could not read calendar block range 1052 ...Retrying in 5 seconds...

### ISSUE THREAD

**Issue by adamluc** [chainpoint/chainpoint-node#67] opened 2017-09-24 16:20 UTC
Just got this message, just updated node via git

chainpoint-node_1  | 2017-09-24T16:17:51.157566806Z CoreHost selected from DNS : c.chainpoint.org

chainpoint-node_1  | 2017-09-24T16:18:05.216952662Z Node startup completed successfully!
chainpoint-node_1  | 2017-09-24T16:18:12.161658870Z Could not read calendar block range 1052 ...Retrying in 5 seconds...

**Comment by kensho2000** [comment] 2017-09-24 16:39
+1

**Comment by banchmax** [comment] 2017-09-24 17:08
+1

**Comment by Octron4** [comment] 2017-09-24 22:09
+1

**Comment by koheihamada** [comment] 2017-09-25 00:45
+1

**Comment by dankadar** [comment] 2017-09-25 01:06
+1

**Comment by serdarozturk** [comment] 2017-09-25 08:45
very bad release. nodes are no longer running. many thanks to the dev team. 

you write "do not lose the private key", you saved it, but you can not use that private key when making the mistake. why? but such functions do not yet exist. like a joke.

and other thing the game starts but the second half of the game rules have changed.

have you guessed that the network will get smaller and the price of TNT will decrease? if investors go, you will not find new investors at these fees.

**Comment by grempe** [comment] 2017-09-26 17:23
Closing as duplicate of issue #69

**Closed by grempe** 2017-09-26 17:23 UTC
