### ISSUE TITLE
Blockrange "n" not ready yet

### ISSUE THREAD

**Issue by 1ce** [chainpoint/chainpoint-node#40] opened 2017-09-20 05:15 UTC

**Comment by mikevdl** [comment] 2017-09-20 07:19
Same error here, on several nodes, since this morning. Nodes were running fine before.. "Blockrange 465 not ready yet"

**Comment by sgarciafer** [comment] 2017-09-20 09:54
Also same error on many old nodes, but the freshly created nodes are passing the audits though.
'Blockrange 466 not ready yet'

**Comment by shinji2000** [comment] 2017-09-20 11:51
Same error

467 not ready yet

**Comment by sima124** [comment] 2017-09-20 12:46
Same error
Blockrange 468 not ready yet

**Comment by takecian** [comment] 2017-09-20 13:09
+1

**Comment by sima124** [comment] 2017-09-20 13:18
> takecian 
https://github.com/chainpoint/chainpoint-node/issues/26

**Comment by grempe** [comment] 2017-09-20 14:52
This is not a bug. It is working as designed. The 'not ready yet' message is informational in nature. You do not need to do anything. It is waiting for a new blockrange to become ready (a block range is 100 contiguous blocks that the Node will pull down and import). It is just informing the node operator that it tried to get the range, it wasn't ready yet. It will retry a few minutes later. Closing.

**Closed by grempe** 2017-09-20 14:52 UTC

**Comment by takecian** [comment] 2017-09-20 15:02
@sima124 thanks, infinite loop fixed by reboot.
