### ISSUE TITLE
Error Performing Calendar Update - Invalid Response 520

### ISSUE THREAD

**Issue by adamluc** [chainpoint/chainpoint-node#16] opened 2017-09-18 02:50 UTC
I have gotten the below error:

chainpoint-node_1  | 2017-09-18T02:47:07.165295177Z Error performing calendar update : Invalid response : 520 : 520 - "<!DOCTYPE html>\n\n\n\n <html class=\"no-js\" lang=\"en-US\"> \n<head>\n<meta http-equiv=\"refresh\" content=\"0\">\n\n<meta http-equiv=\"set-cookie\" content=\"cf_use_ob=443; expires=Mon, 18-Sep-17 02:47:37 GMT; path=/\">\n\n<meta http-equiv=\"set-cookie\" content=\"cf_ob_info=520:3a00fa5c8dff7295:AMS; expires=Mon, 18-Sep-17 02:47:37 GMT; path=/\">\n\n\n<title>b.chainpoint.org | 520: Web server is returning an unknown error</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n\n<script type=\"text/javascript\" src=\"/cdn-cgi/scripts/zepto.min.js\"></script>\n<script type=\"text/javascript\" src=\"/cdn-cgi/scripts/cf.common.js\"></script>\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n\n    \n\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n        <div class=\"cf-wrapper cf-error-overview\">\n            <h1>\n              <span class=\"cf-error-type\" data-translate=\"error\">Error</span>\n              <span class=\"cf-error-code\">520</span>\n              <small class=\"heading-ray-id\">Ray ID: 3a00fa5c8dff7295 &bull; 2017-09-18 02:47:07 UTC</small>\n            </h1>\n            <h2 class=\"cf-subheadline\" data-translate=\"error_desc\">Web server is returning an unknown error</h2>\n        </div>\n\n        <div class=\"cf-section cf-highlight cf-status-display\">\n            <div class=\"cf-wrapper\">\n                <div class=\"cf-columns cols-3\">\n                  \n<div id=\"cf-browser-status\" class=\"cf-column cf-status-item cf-browser-status \">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-browser\"></i>\n    <i class=\"cf-icon-status cf-icon-ok\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"browser_desc\">You</span>\n  <h3 class=\"cf-status-name\" data-translate=\"browser_label\">Browser</h3>\n  <span class=\"cf-status-label\" data-translate=\"browser_status_label\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\"cf-column cf-status-item cf-cloudflare-status \">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-cloud\"></i>\n    <i class=\"cf-icon-status cf-icon-ok\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"cloud_desc\">Amsterdam</span>\n  <h3 class=\"cf-status-name\" data-translate=\"cloud_label\">Cloudflare</h3>\n  <span class=\"cf-status-label\" data-translate=\"cloud_status_label\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-column cf-status-item cf-host-status cf-error-source\">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-server\"></i>\n    <i class=\"cf-icon-status cf-icon-error\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"server_desc\">b.chainpoint.org</span>\n  <h3 class=\"cf-status-name\" data-translate=\"server_label\">Host</h3>\n  <span class=\"cf-status-label\" data-translate=\"server_status_label\">Error</span>\n</div>\n\n                </div>\n            </div>\n        </div>\n\n        <div class=\"cf-section cf-wrapper\">\n            <div class=\"cf-columns two\">\n                <div class=\"cf-column\">\n                    <h2 data-translate=\"what_happened\">What happened?</h2>\n                    <p data-translate=\"unknown_error_desc\">There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>\n                </div>\n\n                <div class=\"cf-column\">\n                    <h2 data-translate=\"what_can_i_do\">What can I do?</h2>\n                          <h5 data-translate=\"if_website_visitor\">If you are a visitor of this website:</h5>\n      <p data-translate=\"try_again_in_a_few\">Please try again in a few minutes.</p>\n\n      <h5 data-translate=\"if_website_owner\">If you are the owner of this website:</h5>\n      <p><span data-translate=\"520_owner_desc\">There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a href=\"https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520\" data-translate=\"addtl_troubleshooting\">Additional troubleshooting resources</a>.</p>\n                </div>\n            </div>\n        </div>\n\n        <div class=\"cf-error-footer cf-wrapper\">\n  <p>\n    <span class=\"cf-footer-item\">Cloudflare Ray ID: <strong>3a00fa5c8dff7295</strong></span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"your_ip\">Your IP</span>: 188.226.164.108</span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"performance_security_by\">Performance &amp; security by</span> <a data-orig-proto=\"https\" data-orig-ref=\"www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div>\n\n\n    </div>\n</div>\n"

**Comment by Richardxlin** [comment] 2017-09-18 02:53
+1

**Comment by Orangem21** [comment] 2017-09-18 06:34
same question

**Comment by Cistor** [comment] 2017-09-18 11:40
Same here : 

chainpoint-node_1  | 2017-09-18T11:39:18.617181707Z Error performing calendar update : Invalid response : 520 : 520 - "<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n<meta http-equiv=\"refresh\" content=\"0\">\n\n<meta http-equiv=\"set-cookie\" content=\"cf_use_ob=443; expires=Mon, 18-Sep-17 11:39:48 GMT; path=/\">\n\n<meta http-equiv=\"set-cookie\" content=\"cf_ob_info=520:3a0405e85e9e0c9b:AMS; expires=Mon, 18-Sep-17 11:39:48 GMT; path=/\">\n\n\n<title>c.chainpoint.org | 520: Web server is returning an unknown error</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n<!--[if lt IE 9]><link rel=\"stylesheet\" id='cf_styles-ie-css' href=\"/cdn-cgi/styles/cf.errors.ie.css\" type=\"text/css\" media=\"screen,projection\" /><![endif]-->\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n<!--[if lte IE 9]><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/jquery.min.js\"></script><![endif]-->\n<!--[if gte IE 10]><!--><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/zepto.min.js\"></script><!--<![endif]-->\n<script type=\"text/javascript\" src=\"/cdn-cgi/scripts/cf.common.js\"></script>\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n\n    \n\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n        <div class=\"cf-wrapper cf-error-overview\">\n            <h1>\n              <span class=\"cf-error-type\" data-translate=\"error\">Error</span>\n              <span class=\"cf-error-code\">520</span>\n              <small class=\"heading-ray-id\">Ray ID: 3a0405e85e9e0c9b &bull; 2017-09-18 11:39:18 UTC</small>\n            </h1>\n            <h2 class=\"cf-subheadline\" data-translate=\"error_desc\">Web server is returning an unknown error</h2>\n        </div><!-- /.error-overview -->\n\n        <div class=\"cf-section cf-highlight cf-status-display\">\n            <div class=\"cf-wrapper\">\n                <div class=\"cf-columns cols-3\">\n                  \n<div id=\"cf-browser-status\" class=\"cf-column cf-status-item cf-browser-status \">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-browser\"></i>\n    <i class=\"cf-icon-status cf-icon-ok\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"browser_desc\">You</span>\n  <h3 class=\"cf-status-name\" data-translate=\"browser_label\">Browser</h3>\n  <span class=\"cf-status-label\" data-translate=\"browser_status_label\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\"cf-column cf-status-item cf-cloudflare-status \">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-cloud\"></i>\n    <i class=\"cf-icon-status cf-icon-ok\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"cloud_desc\">Amsterdam</span>\n  <h3 class=\"cf-status-name\" data-translate=\"cloud_label\">Cloudflare</h3>\n  <span class=\"cf-status-label\" data-translate=\"cloud_status_label\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-column cf-status-item cf-host-status cf-error-source\">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-server\"></i>\n    <i class=\"cf-icon-status cf-icon-error\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"server_desc\">c.chainpoint.org</span>\n  <h3 class=\"cf-status-name\" data-translate=\"server_label\">Host</h3>\n  <span class=\"cf-status-label\" data-translate=\"server_status_label\">Error</span>\n</div>\n\n                </div>\n            </div>\n        </div><!-- /.status-display -->\n\n        <div class=\"cf-section cf-wrapper\">\n            <div class=\"cf-columns two\">\n                <div class=\"cf-column\">\n                    <h2 data-translate=\"what_happened\">What happened?</h2>\n                    <p data-translate=\"unknown_error_desc\">There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>\n                </div>\n\n                <div class=\"cf-column\">\n                    <h2 data-translate=\"what_can_i_do\">What can I do?</h2>\n                          <h5 data-translate=\"if_website_visitor\">If you are a visitor of this website:</h5>\n      <p data-translate=\"try_again_in_a_few\">Please try again in a few minutes.</p>\n\n      <h5 data-translate=\"if_website_owner\">If you are the owner of this website:</h5>\n      <p><span data-translate=\"520_owner_desc\">There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a href=\"https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520\" data-translate=\"addtl_troubleshooting\">Additional troubleshooting resources</a>.</p>\n                </div>\n            </div>\n        </div><!-- /.section -->\n\n        <div class=\"cf-error-footer cf-wrapper\">\n  <p>\n    <span class=\"cf-footer-item\">Cloudflare Ray ID: <strong>3a0405e85e9e0c9b</strong></span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"your_ip\">Your IP</span>: 188.226.153.184</span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"performance_security_by\">Performance &amp; security by</span> <a data-orig-proto=\"https\" data-orig-ref=\"www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div><!-- /.error-footer -->\n\n\n    </div><!-- /#cf-error-details -->\n</div><!-- /#cf-wrapper -->\n"
chainpoint-node_1  | 2017-09-18T11:39:18.629392781Z Error querying for proofs on Core : Invalid response : 520 : 520 - "<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n<meta http-equiv=\"refresh\" content=\"0\">\n\n<meta http-equiv=\"set-cookie\" content=\"cf_use_ob=443; expires=Mon, 18-Sep-17 11:39:48 GMT; path=/\">\n\n<meta http-equiv=\"set-cookie\" content=\"cf_ob_info=520:3a0405cdfd67728f:AMS; expires=Mon, 18-Sep-17 11:39:48 GMT; path=/\">\n\n\n<title>c.chainpoint.org | 520: Web server is returning an unknown error</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n<!--[if lt IE 9]><link rel=\"stylesheet\" id='cf_styles-ie-css' href=\"/cdn-cgi/styles/cf.errors.ie.css\" type=\"text/css\" media=\"screen,projection\" /><![endif]-->\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n<!--[if lte IE 9]><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/jquery.min.js\"></script><![endif]-->\n<!--[if gte IE 10]><!--><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/zepto.min.js\"></script><!--<![endif]-->\n<script type=\"text/javascript\" src=\"/cdn-cgi/scripts/cf.common.js\"></script>\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n\n    \n\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n        <div class=\"cf-wrapper cf-error-overview\">\n            <h1>\n              <span class=\"cf-error-type\" data-translate=\"error\">Error</span>\n              <span class=\"cf-error-code\">520</span>\n              <small class=\"heading-ray-id\">Ray ID: 3a0405cdfd67728f &bull; 2017-09-18 11:39:18 UTC</small>\n            </h1>\n            <h2 class=\"cf-subheadline\" data-translate=\"error_desc\">Web server is returning an unknown error</h2>\n        </div><!-- /.error-overview -->\n\n        <div class=\"cf-section cf-highlight cf-status-display\">\n            <div class=\"cf-wrapper\">\n                <div class=\"cf-columns cols-3\">\n                  \n<div id=\"cf-browser-status\" class=\"cf-column cf-status-item cf-browser-status \">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-browser\"></i>\n    <i class=\"cf-icon-status cf-icon-ok\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"browser_desc\">You</span>\n  <h3 class=\"cf-status-name\" data-translate=\"browser_label\">Browser</h3>\n  <span class=\"cf-status-label\" data-translate=\"browser_status_label\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\"cf-column cf-status-item cf-cloudflare-status \">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-cloud\"></i>\n    <i class=\"cf-icon-status cf-icon-ok\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"cloud_desc\">Amsterdam</span>\n  <h3 class=\"cf-status-name\" data-translate=\"cloud_label\">Cloudflare</h3>\n  <span class=\"cf-status-label\" data-translate=\"cloud_status_label\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-column cf-status-item cf-host-status cf-error-source\">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-server\"></i>\n    <i class=\"cf-icon-status cf-icon-error\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"server_desc\">c.chainpoint.org</span>\n  <h3 class=\"cf-status-name\" data-translate=\"server_label\">Host</h3>\n  <span class=\"cf-status-label\" data-translate=\"server_status_label\">Error</span>\n</div>\n\n                </div>\n            </div>\n        </div><!-- /.status-display -->\n\n        <div class=\"cf-section cf-wrapper\">\n            <div class=\"cf-columns two\">\n                <div class=\"cf-column\">\n                    <h2 data-translate=\"what_happened\">What happened?</h2>\n                    <p data-translate=\"unknown_error_desc\">There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>\n                </div>\n\n                <div class=\"cf-column\">\n                    <h2 data-translate=\"what_can_i_do\">What can I do?</h2>\n                          <h5 data-translate=\"if_website_visitor\">If you are a visitor of this website:</h5>\n      <p data-translate=\"try_again_in_a_few\">Please try again in a few minutes.</p>\n\n      <h5 data-translate=\"if_website_owner\">If you are the owner of this website:</h5>\n      <p><span data-translate=\"520_owner_desc\">There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a href=\"https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520\" data-translate=\"addtl_troubleshooting\">Additional troubleshooting resources</a>.</p>\n                </div>\n            </div>\n        </div><!-- /.section -->\n\n        <div class=\"cf-error-footer cf-wrapper\">\n  <p>\n    <span class=\"cf-footer-item\">Cloudflare Ray ID: <strong>3a0405cdfd67728f</strong></span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"your_ip\">Your IP</span>: 188.226.153.184</span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"performance_security_by\">Performance &amp; security by</span> <a data-orig-proto=\"https\" data-orig-ref=\"www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div><!-- /.error-footer -->\n\n\n    </div><!-- /#cf-error-details -->\n</div><!-- /#cf-wrapper -->\n"
chainpoint-node_1  | 2017-09-18T11:39:23.399849093Z Could not submit hash to Core: Invalid response : 401 : 401 - {"code":"InvalidCredentials","message":"authorization denied: ResourceRequest timed out"}
chainpoint-node_1  | 2017-09-18T11:39:24.591643438Z Error performing calendar update : Invalid response : 521 : 521 - "<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en-US\"> <!--<![endif]-->\n<head>\n<meta http-equiv=\"refresh\" content=\"0\">\n\n<meta http-equiv=\"set-cookie\" content=\"cf_use_ob=443; expires=Mon, 18-Sep-17 11:39:54 GMT; path=/\">\n\n<meta http-equiv=\"set-cookie\" content=\"cf_ob_info=521:3a0406461dac2b70:AMS; expires=Mon, 18-Sep-17 11:39:54 GMT; path=/\">\n\n\n<title>c.chainpoint.org | 521: Web server is down</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n<!--[if lt IE 9]><link rel=\"stylesheet\" id='cf_styles-ie-css' href=\"/cdn-cgi/styles/cf.errors.ie.css\" type=\"text/css\" media=\"screen,projection\" /><![endif]-->\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n<!--[if lte IE 9]><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/jquery.min.js\"></script><![endif]-->\n<!--[if gte IE 10]><!--><script type=\"text/javascript\" src=\"/cdn-cgi/scripts/zepto.min.js\"></script><!--<![endif]-->\n<script type=\"text/javascript\" src=\"/cdn-cgi/scripts/cf.common.js\"></script>\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n\n    \n\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n        <div class=\"cf-wrapper cf-error-overview\">\n            <h1>\n              <span class=\"cf-error-type\" data-translate=\"error\">Error</span>\n              <span class=\"cf-error-code\">521</span>\n              <small class=\"heading-ray-id\">Ray ID: 3a0406461dac2b70 &bull; 2017-09-18 11:39:24 UTC</small>\n            </h1>\n            <h2 class=\"cf-subheadline\" data-translate=\"error_desc\">Web server is down</h2>\n        </div><!-- /.error-overview -->\n\n        <div class=\"cf-section cf-highlight cf-status-display\">\n            <div class=\"cf-wrapper\">\n                <div class=\"cf-columns cols-3\">\n                  \n<div id=\"cf-browser-status\" class=\"cf-column cf-status-item cf-browser-status \">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-browser\"></i>\n    <i class=\"cf-icon-status cf-icon-ok\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"browser_desc\">You</span>\n  <h3 class=\"cf-status-name\" data-translate=\"browser_label\">Browser</h3>\n  <span class=\"cf-status-label\" data-translate=\"browser_status_label\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\"cf-column cf-status-item cf-cloudflare-status \">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-cloud\"></i>\n    <i class=\"cf-icon-status cf-icon-ok\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"cloud_desc\">Amsterdam</span>\n  <h3 class=\"cf-status-name\" data-translate=\"cloud_label\">Cloudflare</h3>\n  <span class=\"cf-status-label\" data-translate=\"cloud_status_label\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-column cf-status-item cf-host-status cf-error-source\">\n  <div class=\"cf-icon-error-container\">\n    <i class=\"cf-icon cf-icon-server\"></i>\n    <i class=\"cf-icon-status cf-icon-error\"></i>\n  </div>\n  <span class=\"cf-status-desc\" data-translate=\"server_desc\">c.chainpoint.org</span>\n  <h3 class=\"cf-status-name\" data-translate=\"server_label\">Host</h3>\n  <span class=\"cf-status-label\" data-translate=\"server_status_label\">Error</span>\n</div>\n\n                </div>\n            </div>\n        </div><!-- /.status-display -->\n\n        <div class=\"cf-section cf-wrapper\">\n            <div class=\"cf-columns two\">\n                <div class=\"cf-column\">\n                    <h2 data-translate=\"what_happened\">What happened?</h2>\n                    <p data-translate=\"not_returning_connection\">The web server is not returning a connection. As a result, the web page is not displaying.</p>\n                </div>\n\n                <div class=\"cf-column\">\n                    <h2 data-translate=\"what_can_i_do\">What can I do?</h2>\n                          <h5 data-translate=\"if_website_visitor\">If you are a visitor of this website:</h5>\n      <p data-translate=\"try_again_in_a_few\">Please try again in a few minutes.</p>\n\n      <h5 data-translate=\"if_website_owner\">If you are the owner of this website:</h5>\n      <p><span data-translate=\"521_owner_desc\">Contact your hosting provider letting them know your web server is not responding.</span> <a data-translate=\"addtl_troubleshooting\" href=\"https://support.cloudflare.com/hc/en-us/articles/200171916-Error-521\">Additional troubleshooting information</a>.</p>\n                </div>\n            </div>\n        </div><!-- /.section -->\n\n        <div class=\"cf-error-footer cf-wrapper\">\n  <p>\n    <span class=\"cf-footer-item\">Cloudflare Ray ID: <strong>3a0406461dac2b70</strong></span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"your_ip\">Your IP</span>: 188.226.153.184</span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"performance_security_by\">Performance &amp; security by</span> <a data-orig-proto=\"https\" data-orig-ref=\"www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div><!-- /.error-footer -->\n\n\n    </div><!-- /#cf-error-details -->\n</div><!-- /#cf-wrapper -->\n"

**Comment by 1ce** [comment] 2017-09-18 15:19
same question

**Comment by muntasirjoarder** [comment] 2017-09-19 01:44
Same problem here

**Comment by tori365** [comment] 2017-09-19 04:36
Same

**Comment by canteboi** [comment] 2017-09-19 13:14
same! any updates is greatly appreciated

**Comment by sgarciafer** [comment] 2017-09-19 19:45
By what I've read, this error is not affecting the node performance and even if it's on their bug log,  is not a priority.

**Comment by grempe** [comment] 2017-09-20 14:55
This issue has been resolved in the latest version of the Node software. Please upgrade as described in the Wiki FAQ page of this repository.

**Closed by grempe** 2017-09-20 14:55 UTC
