### ISSUE TITLE
Node HMAC Does Not Exist: Node Update Destroyed Keys On Small % of Nodes

### ISSUE THREAD

**Issue by accrubit** [chainpoint/chainpoint-node#12] opened 2017-09-17 20:23 UTC
**Important Preface:** _This node was running perfectly prior to upgrade with zero errors since going live. All prior nodes upgraded with no issues to the chainpoint-node directory_

<b>After executing the upgrade node instructions provided, my node lost it's http:// before the URI. This was easily fixed, however I also lost my secret key locally apparently. So if a node upgrades and loses their local key, where do we go to add it again on the local system?</b> @grempe 

The command tree was as follows:

_make down
git pull
make up
make logs_

_Core host selected
Successfully established Postgress connection
A node HMAC does not exist locally for TNT Address "mynodeethwallet"
TNT Address "mynodeethwallet" cannot be registered, it is already registered and in use with an existing HMAC key
Error Command failed with exit code 1._

**Are we supposed to lose unique data in our .env file after reboot? Are we also supposed to lose our local secret key? I had over 100,000 credits in a node and don't want to create another MEW and lose them.**

Ubuntu 16.04 - 512 MB RAM, 1 CPU, 20 GB SSD

**Comment by aona11** [comment] 2017-09-17 21:40
Have the same error too .Hope dev could give us a solution

**Comment by apaticmusic** [comment] 2017-09-17 22:34
As to me. Everything was fine before an update.

chainpoint-node_1  | 2017-09-17T22:36:52.483324887Z CoreHost selected from DNS : a.chainpoint.org
chainpoint-node_1  | 2017-09-17T22:36:52.593980837Z Successfully established Postgres connection
chainpoint-node_1  | 2017-09-17T22:36:52.610947214Z Using existing NodeHMAC for TNT address 0x684d67fb9d729a1073811f188e19565b40a38529
chainpoint-node_1  | 2017-09-17T22:36:52.855301008Z Unable register Node with Core. Retrying in 5 seconds...

**Comment by apaticmusic** [comment] 2017-09-18 20:34
Is it possible to get my credits back on this node?

**Comment by takeratta** [comment] 2017-09-20 06:41
+1

**Comment by serdarozturk** [comment] 2017-09-20 07:17
How we can update hmac key? i saved key but i can not updated on chainpoint-node. What is the command for this issue?

**Comment by serdarozturk** [comment] 2017-09-20 08:11
I solved my problem. But dev team must be add a function for update hmac key. 

If you are using chainpoint-node delete this and install chainpoint-node-src with git clone.

After open server.js

Find this line

`console.error(`TNT address ${env.NODE_TNT_ADDRESS} already exists and cannot be registered.`)`

Paste this code after the line

`wait NodeHMAC.create({ tntAddr: env.NODE_TNT_ADDRESS, hmacKey: 'YOUR_BACKUP_HMAC_KEY' })`

dont forget replace your hmac key with YOUR_BACKUP_HMAC_KEY text.

run make up and thats it.

**Comment by grempe** [comment] 2017-09-20 15:17
While this suggested solution may *appear* to work it is not recommended and will remain unsupported. You are likely to operate a broken Node by doing so.

A better solution will be forthcoming, which will allow you to re-import the Node authentication key into your Node's local database.

Please wait until a proper solution is documented or implemented. You are likely to operate a broken Node when you install from the master branch of the source code repository. We will not provide assistance for these installs.

**Comment by serdarozturk** [comment] 2017-09-21 07:39
@grempe my solution is temporary. you are right. it can be returned to the original code after the problem is fixed.

**Comment by grempe** [comment] 2017-09-21 17:02
No, the point is you should not be operating a Node by running it from the bleeding edge master branch of chainpoint-node-src. Any suggestion to do so is not helpful.

**Comment by grempe** [comment] 2017-09-30 06:22
I have committed, and documented, a method for exporting/importing the authentication keys from a Node's PostgreSQL DB. This change will go out with the next release.

https://github.com/chainpoint/chainpoint-node#node-authentication-keys

**Closed by grempe** 2017-09-30 06:22 UTC
